title: akhilmarakkar.com
description: Weather, where I remember things.
url: "https://akhilmarakkar.com"
baseurl: ""
lang: en
timezone: Asia/Dubai
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-seo-tag
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
